version: 2

sphinx:
  # Path to your Sphinx configuration file.
  configuration: docs/web_documentation/_config.yml

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    pre_build:
      # Generate on-the-fly Sphinx configuration from Jupyter Book's _config.yml
      - "jupyter-book config sphinx docs/web_documentation/"

python:
   install:
   - requirements: docs/web_documentation/requirements.txt
#   - method: pip
#     path: .

formats:
  - pdf
  - epub
